###############################
###############################
##     此插件由曙光編寫      ##
###############################
###############################

#重生點
Spawn:
  World: spawn
  x: -97.5
  y: 79.0
  z: 180.5